Adding fuel changes
fuel-infrastructure/explorer pull request #1
Opened 2024-11-27 17:13 UTC by frangrech

2024-11-27 17:14 UTC, dillu24 commented on README.md
> -
We need to keep this. Can you please keep it and populate it with your list of changes?

2024-11-27 17:15 UTC, dillu24 commented on README.md
> -- Removed Sponsors from DefaultLayout.vue
Can you please keep this?

2024-11-27 17:17 UTC, dillu24 commented on chains/mainnet/fuel.json
Do we need to also add one for testnet?

2024-11-27 17:17 UTC, dillu24 requested changes
Reviewed

2024-11-27 17:21 UTC, dillu24 commented on chains/mainnet/fuel.json
I guess no right coz we don't want to entries on the explorer,  we just want to modify the chain json.

2024-11-27 20:19 UTC, frangrech commented on chains/mainnet/fuel.json
We can add the spec for testnet and use the same explorer URL, then the user can choose between Fuel Mainnet and Fuel Testnet, up to you

2024-11-28 08:16 UTC, dillu24 commented on chains/mainnet/fuel.json
Lets keep separate for now and I'll bring it up with @kribby

2024-11-28 08:16 UTC, merged